// Auto-generated by LibreLane
module udma_uart_tx(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rstn_i,
  output tx_o,
  output busy_o,
  input cfg_en_i,
  input[15:0] cfg_div_i,
  input cfg_parity_en_i,
  input[1:0] cfg_bits_i,
  input cfg_stop_bits_i,
  input[7:0] tx_data_i,
  input tx_valid_i,
  output tx_ready_o
);
endmodule
