// Auto-generated by LibreLane
module udma_uart_rx(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rstn_i,
  input rx_i,
  input[15:0] cfg_div_i,
  input cfg_en_i,
  input cfg_parity_en_i,
  input[1:0] cfg_bits_i,
  input cfg_stop_bits_i,
  output busy_o,
  output err_parity_o,
  output err_overflow_o,
  output char_event_o,
  output[7:0] rx_data_o,
  output rx_valid_o,
  input rx_ready_i
);
endmodule
